In [2]:
import torch
import time

### Basic F'ns

In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 88, -93, -95,  63,  62,   2])

In [3]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [4]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [10]:
linspace = torch.linspace(3, 10, steps = 5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [11]:
logspace = torch.logspace(start = -10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [12]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [14]:
probabilities = torch.tensor([0.1, 0.9])
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
samples

tensor([1, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [15]:
t1 = torch.tensor([1, 2, 3, 4])
t2 = torch.tensor([5, 6])
out = torch.cat((t1, t2), dim=0)
out

tensor([1, 2, 3, 4, 5, 6])

In [16]:
mat1 = torch.tril(torch.ones(5,5))
mat1

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [17]:
mat2 = torch.triu(torch.ones(5,5))
mat2

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [9]:
m1 = torch.zeros(5, 5)
m2 = torch.tril(torch.ones(5, 5)) == 0
out = m1.masked_fill(m2, float('-inf'))
print(m2)
print(out)
out = torch.exp(out)
print(out)

tensor([[False,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [False, False, False,  True,  True],
        [False, False, False, False,  True],
        [False, False, False, False, False]])
tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])
tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


In [11]:
inp = torch.zeros(2, 3, 4)
inp = inp.transpose(0, 2)
print(inp.shape)

torch.Size([4, 3, 2])


In [ ]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.tensor([7, 8, 9])

